name: ceiba
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  dio: ^4.0.4
  provider: ^6.0.2
  mockito: ^5.1.0


dev_dependencies:
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

